WITH ADA.TEXT_IO; USE ADA.TEXT_IO;

PROCEDURE TEST IS
    BOOL_VAR1: BOOLEAN;
    BOOL_VAR2 :BOOLEAN;
    BOOL_VAR3 : BOOLEAN;
    BOOL_VAR4             :                 BOOLEAN;
    BOOL_VAR5:BOOLEAN:=TRUE;
BEGIN
    BOOL_VAR4:=FALSE;
    PUT_LINE(BOOLEAN'IMAGE(BOOL_VAR5));
    PUT_LINE(BOOLEAN'IMAGE(BOOL_VAR4));
END TEST;