Token_test.o : Token_test.cpp Keyword.hpp Operateur.hpp Constante.hpp Token.hpp
	g++ -Wall -c Token_test.cpp

Token_test : Token_test.o
	g++ -Wall Token_test.o -o Token_test

clean :
	rm -f Token_test Token_test.o

	
